def build(bld):
    module= bld.create_ns3_module('ex-webrtc')
    module.env.append_value("CXXFLAGS", "-I/home/zsy/webrtc/src/")
    module.env.append_value("LINKFLAGS", ["-L/home/zsy/webrtc/src/out/m84/obj/"])
    module.env.append_value("LIB", ["webrtc","dl"])
    module.env.append_value('CXXFLAGS', '-DWEBRTC_POSIX')
    module.source = [
    'model/webrtc-config.cc',
    'model/webrtclog.cc',
    'model/webrtc-receiver.cc',
    'model/webrtc-sender.cc', 
    'model/webrtc-tag.cc',
    'model/webrtc-trace.cc',    
    'model/webrtc-util.cc',
    'api/test/create_frame_generator.cc',
    'api/test/network_emulation/network_emulation_interfaces.cc',
    'test/encoder_settings.cc',
    'test/fake_decoder.cc',
    'test/fake_encoder.cc',
    'test/fake_vp8_decoder.cc',
    'test/fake_vp8_encoder.cc',
    'test/field_trial.cc',
    'test/frame_forwarder.cc',
    'test/frame_generator.cc',
    'test/frame_generator_capturer.cc',
    'test/frame_utils.cc',
    'test/goog_cc_printer.cc',
    'test/rtp_header_parser.cc',
    'test/task_queue_for_test.cc',
    'test/test_video_capturer.cc',
    'test/logging/file_log_writer.cc',
    'test/logging/log_writer.cc',
    'test/scenario/call_client.cc',
    'test/scenario/column_printer.cc',
    'test/scenario/hardware_codecs.cc',
    'test/scenario/network_node.cc',
    'test/scenario/performance_stats.cc',
    'test/scenario/scenario_config.cc',
    'test/scenario/stats_collection.cc',
    'test/scenario/video_frame_matcher.cc',
    'test/scenario/video_stream2.cc',
    'test/testsupport/file_utils.cc',
    'test/testsupport/file_utils_override.cc',
    'test/testsupport/ivf_video_frame_generator.cc',
    ]
    headers = bld(features='ns3header')
    headers.module = 'ex-webrtc'
    headers.source = [
    'model/atomic-lock.h',    
    'model/webrtc-config.h',
    'model/webrtc-defines.h',
    'model/webrtclog.h',
    'model/webrtc-receiver.h',
    'model/webrtc-sender.h',     
    'model/webrtc-tag.h',
    'model/webrtc-trace.h',     
    'model/webrtc-util.h',
	]
